require 'json'
require 'pathname'

# Resolve the react_native_pods.rb file using Node
react_native_pods = Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]).strip

load react_native_pods

platform :ios, '14.0'

prepare_react_native_project!
use_modular_headers!

# Optional: Flipper configuration
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# Handling the linkage (frameworks)
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'CuttingHub' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enable Flipper (optional, disable if using frameworks)
    # :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add Firebase dependencies
  pod 'FirebaseCore', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true

  target 'CuttingHubTests' do
    inherit! :complete
    # Pods for testing
  end

  # Post install hook
  post_install do |installer|
    # Ensure that react-native post_install script is run
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # You can also add additional configurations here if necessary
  end
end
